# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(292, 300)
        self.progbar = QtWidgets.QProgressBar(Form)
        self.progbar.setGeometry(QtCore.QRect(30, 267, 261, 20))
        self.progbar.setProperty("value", 0)
        self.progbar.setObjectName("progbar")
        self.input_lbl = QtWidgets.QLabel(Form)
        self.input_lbl.setGeometry(QtCore.QRect(40, 28, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_lbl.setFont(font)
        self.input_lbl.setObjectName("input_lbl")
        self.input_btn = QtWidgets.QPushButton(Form)
        self.input_btn.setGeometry(QtCore.QRect(160, 20, 101, 40))
        self.input_btn.setObjectName("input_btn")
        self.readn_text = QtWidgets.QLineEdit(Form)
        self.readn_text.setGeometry(QtCore.QRect(110, 100, 61, 20))
        self.readn_text.setObjectName("readn_text")
        self.gain_text = QtWidgets.QLineEdit(Form)
        self.gain_text.setGeometry(QtCore.QRect(110, 130, 61, 20))
        self.gain_text.setObjectName("gain_text")
        self.sigma_text = QtWidgets.QLineEdit(Form)
        self.sigma_text.setGeometry(QtCore.QRect(110, 160, 61, 20))
        self.sigma_text.setObjectName("sigma_text")
        self.readn_lbl = QtWidgets.QLabel(Form)
        self.readn_lbl.setGeometry(QtCore.QRect(30, 103, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.readn_lbl.setFont(font)
        self.readn_lbl.setObjectName("readn_lbl")
        self.sigma_lbl = QtWidgets.QLabel(Form)
        self.sigma_lbl.setGeometry(QtCore.QRect(30, 163, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sigma_lbl.setFont(font)
        self.sigma_lbl.setObjectName("sigma_lbl")
        self.gain_lbl = QtWidgets.QLabel(Form)
        self.gain_lbl.setGeometry(QtCore.QRect(30, 133, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gain_lbl.setFont(font)
        self.gain_lbl.setObjectName("gain_lbl")
        self.pars_lbl = QtWidgets.QLabel(Form)
        self.pars_lbl.setGeometry(QtCore.QRect(30, 73, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pars_lbl.setFont(font)
        self.pars_lbl.setObjectName("pars_lbl")
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setGeometry(QtCore.QRect(170, 210, 91, 41))
        self.start_btn.setObjectName("start_btn")
        self.output_btn = QtWidgets.QPushButton(Form)
        self.output_btn.setGeometry(QtCore.QRect(30, 210, 91, 41))
        self.output_btn.setObjectName("output_btn")
        self.line5 = QtWidgets.QFrame(Form)
        self.line5.setEnabled(True)
        self.line5.setGeometry(QtCore.QRect(20, 85, 160, 20))
        self.line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line5.setObjectName("line5")
        self.line8 = QtWidgets.QFrame(Form)
        self.line8.setGeometry(QtCore.QRect(10, 95, 20, 90))
        self.line8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line8.setObjectName("line8")
        self.line7 = QtWidgets.QFrame(Form)
        self.line7.setGeometry(QtCore.QRect(20, 178, 160, 16))
        self.line7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line7.setObjectName("line7")
        self.line6 = QtWidgets.QFrame(Form)
        self.line6.setGeometry(QtCore.QRect(170, 95, 20, 90))
        self.line6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line6.setObjectName("line6")
        self.line4 = QtWidgets.QFrame(Form)
        self.line4.setGeometry(QtCore.QRect(10, 15, 21, 50))
        self.line4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line4.setObjectName("line4")
        self.line3 = QtWidgets.QFrame(Form)
        self.line3.setGeometry(QtCore.QRect(20, 40, 250, 50))
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.line2 = QtWidgets.QFrame(Form)
        self.line2.setGeometry(QtCore.QRect(260, 15, 20, 50))
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.line1 = QtWidgets.QFrame(Form)
        self.line1.setGeometry(QtCore.QRect(20, 6, 250, 20))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.line9 = QtWidgets.QFrame(Form)
        self.line9.setGeometry(QtCore.QRect(20, 195, 251, 20))
        self.line9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line9.setObjectName("line9")
        self.line11 = QtWidgets.QFrame(Form)
        self.line11.setGeometry(QtCore.QRect(20, 250, 251, 15))
        self.line11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line11.setObjectName("line11")
        self.line12 = QtWidgets.QFrame(Form)
        self.line12.setGeometry(QtCore.QRect(20, 205, 3, 51))
        self.line12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line12.setObjectName("line12")
        self.line10 = QtWidgets.QFrame(Form)
        self.line10.setGeometry(QtCore.QRect(270, 205, 3, 51))
        self.line10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line10.setObjectName("line10")
        self.cosm_lbl = QtWidgets.QLabel(Form)
        self.cosm_lbl.setGeometry(QtCore.QRect(190, 150, 91, 20))
        self.cosm_lbl.setObjectName("cosm_lbl")
        self.filename_lbl = QtWidgets.QLabel(Form)
        self.filename_lbl.setGeometry(QtCore.QRect(210, 100, 47, 13))
        self.filename_lbl.setObjectName("filename_lbl")
        self.cosm_val = QtWidgets.QLabel(Form)
        self.cosm_val.setGeometry(QtCore.QRect(190, 170, 91, 20))
        self.cosm_val.setText("")
        self.cosm_val.setObjectName("cosm_val")
        self.filename_val = QtWidgets.QLabel(Form)
        self.filename_val.setGeometry(QtCore.QRect(190, 120, 91, 16))
        self.filename_val.setText("")
        self.filename_val.setObjectName("filename_val")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.input_lbl.setText(_translate("Form", "Input fits files"))
        self.input_btn.setText(_translate("Form", "Load"))
        self.readn_lbl.setText(_translate("Form", "Readnoise"))
        self.sigma_lbl.setText(_translate("Form", "Sigma"))
        self.gain_lbl.setText(_translate("Form", "Gain"))
        self.pars_lbl.setText(_translate("Form", "Parameters:"))
        self.start_btn.setText(_translate("Form", "Remove CR"))
        self.output_btn.setText(_translate("Form", "Ouput directory"))
        self.cosm_lbl.setText(_translate("Form", "Number of cosmics:"))
        self.filename_lbl.setText(_translate("Form", "Filename:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
